#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/private/aliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/private/aliases.zsh"
fi
# Customize to your needs...
alias gst="git status"
alias yu="yaourt -Syua"
alias yi="yaourt -S"
alias ys="yaourt -Ss"
alias zrc="nvim ~/.zshrc"
alias nrc="nvim ~/.config/nvim/init.vim"
alias runs="python manage.py runserver_plus"
alias mig="python manage.py migrate"
alias mkmig="python manage.py makemigrations"
alias dot="cd ~/.dotfiles"

eval $(dircolors ~/.dircolors)
