#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/private/aliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/private/aliases.zsh"
fi

eval $(dircolors ~/.dircolors)

if [[ -s "${ZDOTDIR:-$HOME}/.zaliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zaliases.zsh"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
source ~/.rvm/scripts/rvm
